on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - seek-1.10
  pull_request:
    branches:
      - seek-1.10

steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: seek-1.10
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sjha2048/compseek
        tags: latest
